version: "3.8"
services:
  web:
    build: ./apache-seguro
    ports:
      - "8080:80"
    container_name: web-seguro
    networks:
      - rede-lab-seguro

  database:
    image: mysql:5.7
    container_name: db-seguro
    environment:
      MYSQL_ROOT_PASSWORD: SenhaSegura@123!
      MYSQL_DATABASE: loja
    # ❗ Não expõe porta no host (acesso apenas interno)
    # ports:
    #   - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - rede-lab-seguro

networks:
  rede-lab-seguro:
    driver: bridge
